# NumPy: Libreria de algebra lineal para python

Libreria fundamental para python

Importar NumPy en GCP

In [0]:
import numpy as np

Arreglos NumPy
**Tipo de arreglos**

Vectores de 1 d
Vectores de 2 d

In [0]:
lista=[1,2,3]

In [3]:
np.array(lista)

array([1, 2, 3])

In [0]:
arreglo=np.array(lista)

In [0]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Funciones para generar arreglos

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Función Zeros / Ones

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Función Linspace: retorno de un número de parametros según se indique

In [16]:
np.linspace(0,10,3) #la distancia entre los elementos es la misma

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

Función EYE

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Generación de números aleatorios

In [19]:
np.random.rand()

0.11840188675905916

In [20]:
np.random.rand(5)

array([0.10435853, 0.88630676, 0.61153795, 0.12366741, 0.637179  ])

Crear números aleatorios a partir de una semilla

In [0]:
np.random.seed(10)

In [22]:
np.random.rand(4)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388])

In [23]:
np.random.rand(5,5)

array([[0.49850701, 0.22479665, 0.19806286, 0.76053071, 0.16911084],
       [0.08833981, 0.68535982, 0.95339335, 0.00394827, 0.51219226],
       [0.81262096, 0.61252607, 0.72175532, 0.29187607, 0.91777412],
       [0.71457578, 0.54254437, 0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698, 0.51313824, 0.65039718]])

In [24]:
np.random.rand(2,4,2)

array([[[0.60103895, 0.8052232 ],
        [0.52164715, 0.90864888],
        [0.31923609, 0.09045935],
        [0.30070006, 0.11398436]],

       [[0.82868133, 0.04689632],
        [0.62628715, 0.54758616],
        [0.819287  , 0.19894754],
        [0.8568503 , 0.35165264]]])

Función normal Randn

In [25]:
np.random.randn(2)

array([-0.8169742 ,  1.01961544])

Función Randint

In [26]:
np.random.randint(90,100,10)

array([92, 98, 98, 96, 96, 95, 96, 90, 90, 96])

Atributos y manipulación de los arreglos

Generar tres arreglos

1. Función arange (6)
2. Función randint 0 50 de diez posiciones
3. Función randint 0 50 matriz de 10*10

In [0]:
ar1= np.arange(6)

In [0]:
ar2= np.random.randint(0,50,10)

In [0]:
ar3= np.random.randint(0,50,[10,10])

In [30]:
print(ar1,ar2,ar3)

[0 1 2 3 4 5] [49 15 44 40 42 45 43 33 45 40] [[25  9 37  0 18 23  3 29 16 20]
 [18 48 14 15 17 25 46 48 42 17]
 [32 17 41 16 41 26 12 30 17 17]
 [16  0 31 37  9  0 38 22 32  2]
 [ 3 31 35 27 18 13 43 48 29 45]
 [11 49 22 37 11 21 33 31 43 24]
 [32 37  9 40 37 43 43 26  7  8]
 [21  8 28 45 30 25 25 14 17 21]
 [13 41 33  4 23 30 28 39 27 39]
 [ 9  7 22 32  3  9 12  4 30  6]]


Dimensionalidad de los arreglos

In [31]:
ar1.ndim

1

In [32]:
ar2.ndim

1

In [33]:
ar3.ndim

2

Shape: Forma del arreglo

In [34]:
ar1.shape

(6,)

In [35]:
ar2.shape

(10,)

# Reshape
Retorna un arreglo que contiene los mismos daatos que el arreglo original pero con dimensiones nuevas

In [36]:
ar1

array([0, 1, 2, 3, 4, 5])

In [0]:
ar1=ar1.reshape(2,3)

In [38]:
print(ar1)

[[0 1 2]
 [3 4 5]]


In [39]:
ar1.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
ar1.reshape(6,2) #Es necesario que se cumpla la lista de objetos presente el número de elementos para la nueva dimensión

ValueError: ignored

# MAX, MIN, ARGMAX, ARGMIN

In [0]:
ar2

In [0]:
ar2.max()

In [0]:
ar2.argmax()

In [0]:
ar2.argmin()

In [0]:
ar2.min()

In [0]:
ar3

In [0]:
ar3.max()

In [0]:
ar3.max(axis=0)#valor 0 es por columnas

In [0]:
ar3.max(axis=1)#valor 1 es por filas

In [0]:
ar3.argmax(axis=0)#valor 0 es por columnas

In [0]:
ar3.argmax(axis=1)#valor 1 es por filas

# dtype
Averiguar el tipo de dato de un arreglo

In [0]:
ar1.dtype

Selección condicional

In [0]:
ar=np.arange(10,21)

In [0]:
print(ar)

In [0]:
indices_cod=ar>14
print(indices_cod)

In [0]:
ar[indices_cod]

In [0]:
ar[indices_cod=='false']

In [0]:
ar[(ar>12)&(ar<18)]#número del arreglo entre 12 y 18 abierto

In [0]:
np.where(ar>16)#Recupera los indices donde se cumpla la condición

In [0]:
np.where(ar>16,1,-1)

# Operación con vectores

In [0]:
v1=np.array([2,10,10])
print(v1)

In [0]:
print(2*v1)

In [0]:
v2=np.array([1,2,1])
print(v1)
print(v2)

In [0]:
print(v1+v2)