# NumPy Taller 



#### Importar NumPy como np

In [0]:
import numpy as np

#### Crear un arreglo de 10 ceros 

In [0]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crear un arreglo de 10 unos

In [0]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crear un arreglo de 10 cincos

In [0]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crear un arreglo de los números enteros desde 10 hasta 50 (incluido)

In [0]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Crear un arreglo de todos los números pares entre 10 y 50 (incluido)

In [0]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Crear una matriz de 3x3 con valores desde 0 a 8

In [0]:
matriz = np.arange(0,9).reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crear una matriz identidad de 3x3

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Usar NumPy para generar un número aleatorio entre 0 y 1

In [0]:
np.random.rand(1)

array([0.68442761])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO
# Su resultado será diferente

array([0.13938024])

#### Usar NumPy para generar 25 números aleatorios con una distribución de probabilidad normal

In [0]:
np.random.randn(25)

array([ 2.27296813,  1.67826293, -0.12233043,  1.55729464, -0.54529965,
       -0.30962357, -0.48093858,  0.91446584, -0.59670054,  1.13575022,
       -1.50811256,  0.1354967 ,  0.54453063, -1.42455263, -0.71464291,
        0.1282275 ,  1.7099519 ,  0.16194812,  1.5803819 ,  0.25932668,
        1.5133921 , -0.9144297 , -1.1947313 , -0.24488261, -1.20419483])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO
# Su resultado será diferente

array([-1.60723448,  1.85783081, -2.14544697,  0.77663188, -0.61915835,
        0.52499653, -0.3833644 ,  1.02223757, -0.78965458,  0.26970229,
       -0.88277958,  1.6956793 , -0.96679527, -0.18010509,  0.82531597,
        1.05375325,  0.70396789, -0.12785109,  0.12090562, -1.66501872,
       -0.73229563,  0.78010825, -0.39308434, -0.07028025, -0.34120063])

#### Crear la siguiente matriz:

In [5]:

np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO
# Existen varias soluciones

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Crear un arreglo de 20 elementos linealmente separados entre 0 y 1:

In [0]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy - Índices y Selección

A partir de la siguiente matriz, replique los resultados que se presentan a continuación:

In [0]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# ESCRIBA SU CODIGO AQUI PARA NO BORRAR EL RESULTADO ESPERADO
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# ESCRIBA SU CODIGO AQUI PARA NO BORRAR EL RESULTADO ESPERADO
mat[3][4]

20

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

20

In [0]:
# ESCRIBA SU CODIGO AQUI PARA NO BORRAR EL RESULTADO ESPERADO
 mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[ 2],
       [ 7],
       [12]])

In [0]:
# ESCRIBA SU CODIGO AQUI PARA NO BORRAR EL RESULTADO ESPERADO
mat[4:,:]

array([[21, 22, 23, 24, 25]])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([21, 22, 23, 24, 25])

In [0]:
# ESCRIBA SU CODIGO AQUI PARA NO BORRAR EL RESULTADO ESPERADO
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy - Operaciones

#### Obtener la suma de todos los valores de la matriz 'mat'

In [0]:
mat.sum()

325

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

325

#### Obtener las desviación estándar de los valores en la matriz 'mat'

In [0]:
mat.std()

7.211102550927978

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

7.211102550927978

#### Obtener la suma de los valores en cada columna de la matriz

In [0]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [0]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([55, 60, 65, 70, 75])